baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Speed of Eve'
theme = 'book'

[services]
  [services.utterances]
    repo = 'https://github.com/TheMoxyFoxy/speedofeve'

[params]
  BookSection = 'posts'